apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-app
  namespace: microdegree
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chatbot
  template:
    metadata:
      labels:
        app: chatbot
    spec:
      containers:
      - name: chatbot-container
        image: arulgun/mddevopsmasterclass:latest # The Jenkinsfile will automatically replace this tag
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
        ports:
        - containerPort: 8501
---
apiVersion: v1
kind: Service
metadata:
  name: chatbot-service
  namespace: microdegree
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8501
  selector:
    app: chatbot