pipeline {
    agent any
    
    environment {
        IMAGE_NAME   = "arulgun/mddevopsmasterclass:${GIT_COMMIT}"
        EKS_ENDPOINT = "https://726C0A19F2162CE71D70AFE61DAFBD1B.gr7.ap-southeast-2.eks.amazonaws.com"
        CLUSTER_NAME = "app"
        NAMESPACE    = "microdegree"
    } 

    stages {
        stage('Git-Checkout') {
            steps {
                git url: 'https://github.com/Arul-pro/Myproject-.git', branch: 'main'
            }
        }

        stage('Build') {
            steps {
                sh '''
                    printenv
                    pwd
                    cd code/
                    docker build -t ${IMAGE_NAME} .
                '''
            }
        }

        stage('Docker Hub Login') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'docker-hub-creds', passwordVariable: 'DOCKER_PASSWORD', usernameVariable: 'DOCKER_USERNAME')]) {
                    sh 'echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin'
                }
            }
        }

        stage('Pushing to Registry'){
            steps{
                sh '''
                    docker push ${IMAGE_NAME}
                '''
            }
        }
        
                    }
                }
                    
                
                
    